### PR TITLE
PA2

### PR DESCRIPTION
**Pull request by rodrigovaldes**
PA2

### CODE REVIEW

**Comment by gingcee** [comment]
This was late. You will receive 2 points off.
@reubenbauer

**Comment by rodrigovaldes** [comment]
@gingcee @reubenbauer

The pull request was made at 11:27 am. I know that it is not in the appropriate folder, but it was before the deadline.

**Comment by rodrigovaldes** [comment]
screen shot 2017-01-23 at 1 19 26 pm

The timestamp as a reference.

**Comment by gingcee** [comment]
Rodrigo, these last two pull requests (including Chih yu's pull request on your behalf) appeared after the class began at 11:31a, which means modifications were made prior to the start of class.

We will not deduct points this time for you on being late, but in the future please note that changes to the pull request that come in after the class time are considered "late."

You will be deducted 1 point for folder organization.
@reubenbauer

**Pull request merged**
